### PR TITLE
Added firestore

### PR DESCRIPTION
**Pull request by sujay1844**
Solves #1

### CODE REVIEW

**Comment by sujay1844** [comment]
Files didn't play well with firebase. I'm making the user input the image url

**Comment by sujay1844** [comment]
and the home page fetches from the database. So extra points?

**Comment by anuragrao04** [comment]
100 base + 20 for file storage using storage bucket + 20 for fetching data on homepage from db

**Comment by anuragrao04** [comment]
!bounty 140

**Pull request merged**
